# Generated by Django 5.2.10 on 2026-01-13 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('dealer_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(
                    choices=[
                        ('Sedan', 'Sedan'),
                        ('SUV', 'SUV'),
                        ('Wagon', 'Wagon'),
                        ('Hatchback', 'Hatchback'),
                        ('Coupe', 'Coupe')
                    ],
                    max_length=20
                )),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(
                    blank=True,
                    decimal_places=2,
                    max_digits=10,
                    null=True
                )),
                ('description', models.TextField(blank=True)),
                ('car_make', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='models',
                    to='djangoapp.carmake'
                )),
            ],
        ),
    ]
